image: fedora

tasks:
  - name: Setup Flatpak
    command: |
      sudo apt update; sudo apt upgrade -y
      sudo add-apt-repository ppa:flatpak/stable -y
      sudo apt update; sudo apt upgrade -y
      sudo apt install flatpak flatpak-builder -y
      sudo flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo

vscode:
  extensions:
    - prince781.vala
    - asabil.meson
    - bilelmoussaoui.flatpak-vscode
