name: Flatpak

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.ui'
      - '**.svg'
      - '**/.gitpod.yml'
      - '**/.gitpod/**'
      - '.github/workflows/windows.yml'

jobs:
  flatpak:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          manifest-path: io.github.Miqueas.TapeDeck.yml
          bundle: io.github.Miqueas.TapeDeck.flatpak
          repository-name: gnome-nightly
          branch: main
