name: Windows

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.ui'
      - '**.svg'
      - '**/.gitpod.*'

jobs:
  # TODO: Write a "test" job I guess
  build:
    runs-on: windows-latest

    defaults:
      run:
        # Sets the default shell where commands will be executed
        shell: msys2 {0}

    steps:
      - name: Setup MSYS
        uses: msys2/setup-msys2@v2
        with:
          path-type: strict
          msystem: MINGW64
          update: true
          install: git base-devel
          pacboy: >
            gcc:x gtk4:x gstreamer:x vala:x meson:x
            ninja:x sassc:x gobject-introspection:x

        # * Tape Deck has the .wrap files for this dependencies, so
        # * maybe i'll remove this commands later
      - name: Clone, build and install libadwaita
        run: |
          git clone https://gitlab.gnome.org/GNOME/libadwaita.git
          cd libadwaita
          git checkout -b gtk4.4-dep 12a10b320300ec32d480c29f26ae55c1d4b2a8b7
          CC=gcc meson BUILD -Dtests=false -Dexamples=false -Dinspector=false
          ninja -C BUILD install
          cd ..; rm -rf libadwaita

      - name: Clone, build and install libmpdclient
        run: |
          git clone https://github.com/MusicPlayerDaemon/libmpdclient.git
          cd libmpdclient
          CC=gcc meson BUILD
          ninja -C BUILD install
          cd ..; rm -rf libmpdclient

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build Tape Deck
        run: |
          CC=gcc meson BUILD
          ninja -C BUILD
