name: Windows

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.ui'
      - '**.svg'
      - '**/.gitpod.yml'
      - '**/.gitpod/**'
      - 'flatpak/com.github.Miqueas.TapeDeck.yml'
      - '.github/workflows/flatpak.yml'

jobs:
  windows:
    name: Build
    runs-on: windows-latest

    defaults:
      run:
        # Sets the default shell where commands will be executed
        shell: msys2 {0}

    steps:
      - name: Setup MSYS
        uses: msys2/setup-msys2@v2
        with:
          path-type: strict
          msystem: MINGW64
          update: true
          install: git base-devel
          pacboy: >
            gcc:x gtk4:x vala:x meson:x
            ninja:x gobject-introspection:x
            libadwaita:x python-gobject:x

      - name: Clone, build and install libmpdclient
        run: |
          git clone https://github.com/MusicPlayerDaemon/libmpdclient.git
          cd libmpdclient
          CC=gcc meson BUILD
          ninja -C BUILD install
          cd ..; rm -rf libmpdclient

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build Tape Deck
        run: |
          CC=gcc meson BUILD
          ninja -C BUILD
